name: Knock Receiver

on:
  status:

permissions: {}

jobs:
  receive-knock:
    # Ignore every status except our dedicated channel.
    if: github.event.context == 'knock'
    runs-on: ubuntu-latest

    steps:
      - name: Receive knock
        run: |
          echo "KNOCK RECEIVED"
          echo "Value: ${{ github.event.description }}"
          echo "State: ${{ github.event.state }}"
          echo "SHA: ${{ github.event.sha }}"
